# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Vineet Loyer Homepage
description: >- # this means to ignore newlines until "baseurl:"
  Data Scientist
baseurl: "" # the subpath of the site
url: "https://Vineet-Loyer.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Education
    - name: Work
    - name: Blog
    - name: Photography 
    

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: vineet.loyer@gmail.com
      link: mailto:vineet.loyer@gmail.com    
      link: "#"
  follow:
    - name: Facebook
      link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: http://linkedin.com/in/Vineet-Loyer
    - name: GitHub
      link: http://github.com/Vineet-Loyer
    

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
